tutorial_questions = [
    "Hi there, what time is my flight?",
    "Am i allowed to update my flight to something sooner? I want to leave later today.",
    "Update my flight to sometime next week then",
    "The next available option is great",
    "what about lodging and transportation?",
    "Yeah i think i'd like an affordable hotel for my week-long stay (7 days). And I'll want to rent a car.",
    "OK could you place a reservation for your recommended hotel? It sounds nice.",
    "yes go ahead and book anything that's moderate expense and has availability.",
    "Now for a car, what are my options?",
    "Awesome let's just get the cheapest option. Go ahead and book for 7 days",
    "Cool so now what recommendations do you have on excursions?",
    "Are they available while I'm there?",
    "interesting - i like the museums, what options are there? ",
    "OK great pick one and book it for my second day there.",
    "Can you provide me with the details of my flight, including the flight number and departure time?",
    "Are there any earlier flights available today?",
    "Can I change my return flight to a later date next week?",
    "What hotels are available in the area? Can you send me a list?",
    "How far is the hotel from the airport? Is transportation provided?",
    "Can you suggest a rental car that’s fuel-efficient and affordable?",
    "Can you confirm the car rental reservation for me once it’s done?",
    "Are there any discounts or deals available for attractions and tours?",
    "What’s the best way to get around the city? Should I use public transportation or rely on my rental car?",
    "Do you have any recommendations for a good restaurant near the hotel?",
    "Are there any free or budget-friendly activities I can do in the city?",
    "What’s the weather forecast during my stay?",
    "Are there any events or festivals happening while I’m there?",
    "Can you book tickets for a specific event or concert I’m interested in?",
    "Can you help me find a spa or wellness center in the area?",
    "Can I upgrade my flight or hotel to first-class or a suite?",
    "Are there any cultural experiences or local tours I should check out?",
    "How can I make sure I don’t miss my flight?",
    "Can you help me with local SIM card or internet access while I’m there?",
    "What time do I need to check out of the hotel on my last day?",
]

